### ISSUE TITLE
Difference to autoflakes

### ISSUE THREAD

**Issue by sils** [myint/vulture#1]
Is there any difference to the autoflakes project? Why not joining them for a better user experience?

**Comment by myint** [comment]
I don't think they are related very much at all. autoflake modifies code whereas vulture is an analyzer.

autoflake fixes items reported by pyflakes. One of the several things pyflakes can do is find unused variables in a function scope. vulture finds unused classes and member variables. pyflakes and vulture don't really overlap in what they detect.

**Comment by sils** [comment]
ok cool, but wouldn't it make sense if vulture could detect issues that are fixable by autoflakes and vice versa, i.e. implementing fixes for vulture issues?

**Comment by myint** [comment]
I see what you mean. I think the problem with automatically fixing vulture issues is the false positive rate of vulture. With pyflakes, if a local variable is not used and we can usually remove it safetly and easily. We can probably assume that no other project is somehow accessing that local variable. But if vulture reports an unused member variable, it could mean it is unused. But it could also be that some other project actually references that unused member variable.

**Comment by sils** [comment]
I do think this is solvable though but that is the coala discussion I started in an email to you and another bug report so no need to annoy you with this here - thanks!
