### ISSUE TITLE
differences to upstream?

### ISSUE THREAD

**Issue by johnyf** [myint/vulture#3]
[Upstream](https://bitbucket.org/jendrikseipp/vulture) appears to be active, and available on [PyPI](https://pypi.python.org/pypi/vulture).
Does this fork contain functionality that should be preferred to using upstream?

**Comment by myint** [comment]
There are very few differences. This fork just adds some pragmatic features that the original author did not want to add. For example [searching for Python scripts without the `.py` extension](https://bitbucket.org/jendrikseipp/vulture/issues/6/doesnt-search-for-scripts-without-py).

**Comment by johnyf** [comment]
Thanks for the clarification.
